export default
{
    "physics":{
        "renderer":{
            "enabled":true,
            "type_lineto":false,
            "type_native":true
        },
        "simulation":{
            "constraintIterations":5
        },
        "gravity":0,
        "move_objects_with_mouse":true
    },
    "app":{
        "debug_rotation":false
    },
    "stats":{
        "enabled":true
    },
    "dat_gui":{
        "enabled":true,
        "closed":true
    },
    "view":{
        "colors":{
            "vertices":{
                "default":"#228855",
                "highlight":"#20f046"
            }
        }
    }
}
